version: "3.7"

services:
  mysql-db:
    image: mysql:5.7
    command: --init-file /data/app/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: VejdKfq4FRvKEGuseHx1VQ==
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser#1812
      MYSQL_DATABASE: Proposals_MRS
    volumes:
      - proposalmgr-db:/var/lib/mysql
    configs:
      - source: db-conf
        target: /data/app/init.sql

  server:
    image: proposalmgr
    depends_on:
      - mysql-db
    #command: build
    env_file: .env.production
    ports:
      - "7000:8000"
    configs:
      - source: webpack-config
        target: /app/webpack.config.js
      - source: db-credentials
        target: /app/src/server/db_credentials.js

volumes:
  proposalmgr-db:
    external: true
 
configs:
  db-conf:
    file: ./init.sql
  webpack-config:
    file: ./webpack.config.js
  db-credentials:
    file: ./db_credentials.js

