FROM mysql:latest   

ENV MYSQL_ROOT_PASSWORD 123             
ENV MYSQL_DATAVBASE dockerdb               
ENV MYSQL_USER hengzhi                          
ENV MYSQL_PASSWORD 123456                

EXPOSE 3306   

